# Generated by Django 5.2.1 on 2025-05-22 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(help_text='Nombres del usuario', max_length=45, verbose_name='Nombres')),
                ('apellidos', models.CharField(help_text='Apellidos del usuario', max_length=45, verbose_name='Apellidos')),
                ('promedio', models.FloatField(blank=True, help_text='Promedio del usuario (si aplica)', null=True, verbose_name='Promedio académico')),
                ('disponibilidad', models.BooleanField(default=True, help_text='Indica si el usuario está disponible', verbose_name='¿Está disponible?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de autenticación')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
    ]
