# Generated by Django 4.1.7 on 2025-05-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_alter_usuario_managers_remove_usuario_apellidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
