# Generated by Django 5.2.1 on 2025-05-24 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_remove_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre legible del recurso', max_length=100, unique=True)),
                ('url', models.CharField(help_text='Ruta del backend sin dominio, ej: /api/entrenamientos/', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecursoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='autenticacion.recurso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='autenticacion.rol')),
            ],
            options={
                'unique_together': {('rol', 'recurso')},
            },
        ),
    ]
