# Generated by Django 5.2.1 on 2025-07-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reproduccion',
            name='animal',
        ),
        migrations.AddField(
            model_name='reproduccion',
            name='animales',
            field=models.ManyToManyField(related_name='reproducciones', to='funcionalidad.animal'),
        ),
    ]
