# Generated by Django 5.2.1 on 2025-07-17 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidad', '0002_remove_reproduccion_animal_reproduccion_animales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='estado_reproductivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales_estado_reproductivo', to='funcionalidad.tablamaestra'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='estado_salud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales_estado_salud', to='funcionalidad.tablamaestra'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales_raza', to='funcionalidad.tablamaestra'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales_sexo', to='funcionalidad.tablamaestra'),
        ),
    ]
