# Generated by Django 5.2.1 on 2025-07-17 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidad', '0003_alter_animal_estado_reproductivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='animales_especie', to='funcionalidad.tablamaestra'),
            preserve_default=False,
        ),
    ]
