// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClDrgiHJ7KjMn1LRwxSQGql5DbVAKxKKc',
    appId: '1:518859406805:web:773cd4494ff2139125d15c',
    messagingSenderId: '518859406805',
    projectId: 'ganadera-4b6d7',
    authDomain: 'ganadera-4b6d7.firebaseapp.com',
    storageBucket: 'ganadera-4b6d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1mC5b4_BFhqequVjHc9tSDbpkujU-apQ',
    appId: '1:518859406805:android:0a78fa9ffc62563b25d15c',
    messagingSenderId: '518859406805',
    projectId: 'ganadera-4b6d7',
    storageBucket: 'ganadera-4b6d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhq6xdAkhRq2rtOEoNBYqEsvt1R859Y4A',
    appId: '1:518859406805:ios:02a44b8993b2883625d15c',
    messagingSenderId: '518859406805',
    projectId: 'ganadera-4b6d7',
    storageBucket: 'ganadera-4b6d7.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhq6xdAkhRq2rtOEoNBYqEsvt1R859Y4A',
    appId: '1:518859406805:ios:02a44b8993b2883625d15c',
    messagingSenderId: '518859406805',
    projectId: 'ganadera-4b6d7',
    storageBucket: 'ganadera-4b6d7.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClDrgiHJ7KjMn1LRwxSQGql5DbVAKxKKc',
    appId: '1:518859406805:web:84ad3fb7ae62b87e25d15c',
    messagingSenderId: '518859406805',
    projectId: 'ganadera-4b6d7',
    authDomain: 'ganadera-4b6d7.firebaseapp.com',
    storageBucket: 'ganadera-4b6d7.firebasestorage.app',
  );
}
