# Generated by Django 5.2.1 on 2025-05-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producrtos',
            new_name='Productos',
        ),
    ]
